### ISSUE TITLE
Startup Crash (Seemingly incompatible with lwjgl3ify?)

### ISSUE THREAD

**Issue by DerCommander323** [FalsePattern/FalsePatternLib#23]
The mod causes a crash almost immediately after clicking the start button.

fml-client-latest.log: https://mclo.gs/1rbQNf9
the log that prism launcher gave me: https://mclo.gs/ycmekZ6 (it seems to not be latest.log, since that one only contains like 6 lines, but i almost never play 1.7, so idk how logs work here)

I've tried both UniMixins and GasStation, both give the same crash log. (At least if you get gasstation to load in the correct order with gtnhmixins)

**Comment by DerCommander323** [comment]
The game starts succesfully with just lwjgl3ify + gtnhmixins or unimixins
FalsePatternLib version: I tried 0.10.15 and 0.10.14, both crash the same way.

**Comment by n0099** [comment]
Same here, and I'm using java19:
```log
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:474) ~[?:?]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:461) ~[lwjgl3ify-1.3.1-forgePatches.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:371) ~[lwjgl3ify-1.3.1-forgePatches.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:201) ~[lwjgl3ify-1.3.1-forgePatches.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at com.falsepattern.lib.config.ConfigurationManager.selfInit(ConfigurationManager.java:59) ~[ConfigurationManager.class:?]
	at com.falsepattern.lib.internal.config.LibraryConfig.<clinit>(LibraryConfig.java:31) ~[LibraryConfig.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.validateDownloadsAllowed(DependencyLoaderImpl.java:331) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.load(DependencyLoaderImpl.java:201) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.access$000(DependencyLoaderImpl.java:168) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.lambda$loadLibrariesAsync$1(DependencyLoaderImpl.java:162) ~[DependencyLoaderImpl.class:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: modifiers
	at com.falsepattern.lib.internal.ReflectionUtil.<clinit>(ReflectionUtil.java:36) ~[ReflectionUtil.class:?]
	at com.falsepattern.lib.config.ConfigurationManager.selfInit(ConfigurationManager.java:59) ~[ConfigurationManager.class:?]
	at com.falsepattern.lib.internal.config.LibraryConfig.<clinit>(LibraryConfig.java:31) ~[LibraryConfig.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.validateDownloadsAllowed(DependencyLoaderImpl.java:331) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.load(DependencyLoaderImpl.java:201) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.access$000(DependencyLoaderImpl.java:168) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.lambda$loadLibrariesAsync$1(DependencyLoaderImpl.java:162) ~[DependencyLoaderImpl.class:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2663) ~[?:?]
	at com.falsepattern.lib.internal.ReflectionUtil.<clinit>(ReflectionUtil.java:34) ~[ReflectionUtil.class:?]
	at com.falsepattern.lib.config.ConfigurationManager.selfInit(ConfigurationManager.java:59) ~[ConfigurationManager.class:?]
	at com.falsepattern.lib.internal.config.LibraryConfig.<clinit>(LibraryConfig.java:31) ~[LibraryConfig.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.validateDownloadsAllowed(DependencyLoaderImpl.java:331) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.load(DependencyLoaderImpl.java:201) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl$DependencyLoadTask.access$000(DependencyLoaderImpl.java:168) ~[DependencyLoaderImpl$DependencyLoadTask.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.lambda$loadLibrariesAsync$1(DependencyLoaderImpl.java:162) ~[DependencyLoaderImpl.class:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by FalsePattern** [comment]
Known issue, will be fixed in 0.11.
The fix commit: e2391713c2be0f714fddece51287247d0ab9f056

**Comment by FalsePattern** [comment]
Fixed in 0.11.0

**Comment by DerCommander323** [comment]
That did indeed fix it. Thanks!

**Comment by n0099** [comment]
I'm trying to use [`leafculling-mc1.7.10-2.0.3b.jar`](https://github.com/basdxz/LeafCulling/releases/tag/2.0.3b) and [`falsepatternlib-mc1.7.10-0.11.0.jar`](https://github.com/FalsePattern/FalsePatternLib/releases/tag/0.11.0) with the [GTNH modpack](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack), it still fails to launch for me:
```
[22:13:19] [main/ERROR] [FalsePatternLib Library Loader]: Failed to open jar file /GTNH/.minecraft/mods/CoFHCore-%5B1.7.10%5D3.1.4-329.jar
[22:13:19] [main/ERROR] [FalsePatternLib Library Loader]: Failed to open jar file /GTNH/.minecraft/mods/BiblioCraft%5Bv1.11.7%5D%5BMC1.7.10%5D.jar
[22:13:19] [main/ERROR] [FalsePatternLib Library Loader]: Failed to open jar file /GTNH/.minecraft/mods/BiblioWoods%5BBiomesOPlenty%5D%5Bv1.9%5D.jar
[22:13:19] [main/ERROR] [FalsePatternLib Library Loader]: Failed to open jar file /GTNH/.minecraft/mods/BiblioWoods%5BForestry%5D%5Bv1.7%5D.jar
[22:13:19] [main/ERROR] [FalsePatternLib Library Loader]: Failed to open jar file /GTNH/.minecraft/mods/BiblioWoods%5BNatura%5D%5Bv1.5%5D.jar
[22:13:19] [main/ERROR] [FalsePatternLib Library Loader]: Failed to open jar file /GTNH/.minecraft/mods/CoFHCore-%5B1.7.10%5D3.1.4-329.jar
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.ExceptionInInitializerError
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.forName0(Native Method)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.forName(Class.java:495)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.forName(Class.java:474)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:461)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:371)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:201)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: Caused by: java.lang.IllegalStateException: Not a JSON Object: [{"name":"java.io.FileDescriptor","fields":[{"name":"fd"}],"methods":[{"name":"attach","parameterTypes":["java.io.Closeable"]}]},{"name":"java.lang.Boolean","methods":[{"name":"getBoolean","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.IllegalStateException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.IndexOutOfBoundsException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.Integer","methods":[{"name":"<init>","parameterTypes":["int"]},{"name":"intValue","parameterTypes":[]}]},{"name":"java.lang.NullPointerException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.ProcessBuilder$RedirectPipeImpl","fields":[{"name":"fd"}],"methods":[{"name":"<init>","parameterTypes":[]}]},{"name":"java.lang.String","methods":[{"name":"lastIndexOf","parameterTypes":["int"]},{"name":"substring","parameterTypes":["int"]}]},{"name":"java.lang.System","methods":[{"name":"getProperty","parameterTypes":["java.lang.String"]},{"name":"setProperty","parameterTypes":["java.lang.String","java.lang.String"]}]},{"name":"java.net.DatagramSocket"},{"name":"java.net.InetSocketAddress","fields":[{"name":"holder"}]},{"name":"java.net.InetSocketAddress$InetSocketAddressHolder","fields":[{"name":"port"}]},{"name":"java.net.NoRouteToHostException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.net.ServerSocket","fields":[{"name":"impl"}]},{"name":"java.net.Socket"},{"name":"java.net.SocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.net.SocketTimeoutException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.nio.channels.ClosedChannelException","methods":[{"name":"<init>","parameterTypes":[]}]},{"name":"java.nio.channels.spi.AbstractSelectableChannel","methods":[{"name":"removeKey","parameterTypes":["java.nio.channels.SelectionKey"]}]},{"name":"org.newsclub.net.unix.AFSelector$PollFd","fields":[{"name":"fds"},{"name":"ops"},{"name":"rops"}]},{"name":"org.newsclub.net.unix.AFTIPCSocketAddress"},{"name":"org.newsclub.net.unix.AFUNIXDatagramSocket"},{"name":"org.newsclub.net.unix.AFUNIXServerSocket"},{"name":"org.newsclub.net.unix.AFUNIXSocket"},{"name":"org.newsclub.net.unix.AFUNIXSocketAddress"},{"name":"org.newsclub.net.unix.AFUNIXSocketCredentials","fields":[{"name":"gids"},{"name":"pid"},{"name":"uid"}],"methods":[{"name":"setUUID","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.AddressUnavailableSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.AncillaryDataSupport","fields":[{"name":"ancillaryReceiveBuffer"},{"name":"pendingFileDescriptors"}],"methods":[{"name":"receiveFileDescriptors","parameterTypes":["int[]"]},{"name":"setTipcDestName","parameterTypes":["int","int","int"]},{"name":"setTipcErrorInfo","parameterTypes":["int","int"]}]},{"name":"org.newsclub.net.unix.InvalidArgumentSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.OperationNotSupportedSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.tipc.AFTIPCDatagramSocket"},{"name":"org.newsclub.net.unix.tipc.AFTIPCGroupRequest","methods":[{"name":"fromNative","parameterTypes":["int","int","int","int"]},{"name":"getFlagsValue","parameterTypes":[]},{"name":"getInstance","parameterTypes":[]},{"name":"getScopeId","parameterTypes":[]},{"name":"getType","parameterTypes":[]}]},{"name":"org.newsclub.net.unix.tipc.AFTIPCSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKDatagramSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKServerSocket"}]
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.lambda$scanDeps$5(DependencyLoaderImpl.java:287)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.scanDeps(DependencyLoaderImpl.java:309)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.falsepattern.lib.internal.asm.CoreLoadingPlugin.<clinit>(CoreLoadingPlugin.java:56)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	... 18 more
[22:13:19] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at \GTNH\.minecraft for Forge Mod Loader
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:474) ~[?:?]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:461) ~[lwjgl3ify-1.3.1-forgePatches.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:371) ~[lwjgl3ify-1.3.1-forgePatches.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:201) ~[lwjgl3ify-1.3.1-forgePatches.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Not a JSON Object: [{"name":"java.io.FileDescriptor","fields":[{"name":"fd"}],"methods":[{"name":"attach","parameterTypes":["java.io.Closeable"]}]},{"name":"java.lang.Boolean","methods":[{"name":"getBoolean","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.IllegalStateException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.IndexOutOfBoundsException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.Integer","methods":[{"name":"<init>","parameterTypes":["int"]},{"name":"intValue","parameterTypes":[]}]},{"name":"java.lang.NullPointerException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.ProcessBuilder$RedirectPipeImpl","fields":[{"name":"fd"}],"methods":[{"name":"<init>","parameterTypes":[]}]},{"name":"java.lang.String","methods":[{"name":"lastIndexOf","parameterTypes":["int"]},{"name":"substring","parameterTypes":["int"]}]},{"name":"java.lang.System","methods":[{"name":"getProperty","parameterTypes":["java.lang.String"]},{"name":"setProperty","parameterTypes":["java.lang.String","java.lang.String"]}]},{"name":"java.net.DatagramSocket"},{"name":"java.net.InetSocketAddress","fields":[{"name":"holder"}]},{"name":"java.net.InetSocketAddress$InetSocketAddressHolder","fields":[{"name":"port"}]},{"name":"java.net.NoRouteToHostException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.net.ServerSocket","fields":[{"name":"impl"}]},{"name":"java.net.Socket"},{"name":"java.net.SocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.net.SocketTimeoutException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.nio.channels.ClosedChannelException","methods":[{"name":"<init>","parameterTypes":[]}]},{"name":"java.nio.channels.spi.AbstractSelectableChannel","methods":[{"name":"removeKey","parameterTypes":["java.nio.channels.SelectionKey"]}]},{"name":"org.newsclub.net.unix.AFSelector$PollFd","fields":[{"name":"fds"},{"name":"ops"},{"name":"rops"}]},{"name":"org.newsclub.net.unix.AFTIPCSocketAddress"},{"name":"org.newsclub.net.unix.AFUNIXDatagramSocket"},{"name":"org.newsclub.net.unix.AFUNIXServerSocket"},{"name":"org.newsclub.net.unix.AFUNIXSocket"},{"name":"org.newsclub.net.unix.AFUNIXSocketAddress"},{"name":"org.newsclub.net.unix.AFUNIXSocketCredentials","fields":[{"name":"gids"},{"name":"pid"},{"name":"uid"}],"methods":[{"name":"setUUID","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.AddressUnavailableSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.AncillaryDataSupport","fields":[{"name":"ancillaryReceiveBuffer"},{"name":"pendingFileDescriptors"}],"methods":[{"name":"receiveFileDescriptors","parameterTypes":["int[]"]},{"name":"setTipcDestName","parameterTypes":["int","int","int"]},{"name":"setTipcErrorInfo","parameterTypes":["int","int"]}]},{"name":"org.newsclub.net.unix.InvalidArgumentSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.OperationNotSupportedSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.tipc.AFTIPCDatagramSocket"},{"name":"org.newsclub.net.unix.tipc.AFTIPCGroupRequest","methods":[{"name":"fromNative","parameterTypes":["int","int","int","int"]},{"name":"getFlagsValue","parameterTypes":[]},{"name":"getInstance","parameterTypes":[]},{"name":"getScopeId","parameterTypes":[]},{"name":"getType","parameterTypes":[]}]},{"name":"org.newsclub.net.unix.tipc.AFTIPCSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKDatagramSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKServerSocket"}]
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[JsonElement.class:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.lambda$scanDeps$5(DependencyLoaderImpl.java:287) ~[DependencyLoaderImpl.class:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.scanDeps(DependencyLoaderImpl.java:309) ~[DependencyLoaderImpl.class:?]
	at com.falsepattern.lib.internal.asm.CoreLoadingPlugin.<clinit>(CoreLoadingPlugin.java:56) ~[falsepatternlib-mc1.7.10-0.11.0.jar:?]
	... 18 more
[22:13:19] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:227]: Failed to start Minecraft:
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.ExceptionInInitializerError
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.forName0(Native Method)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.forName(Class.java:495)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.forName(Class.java:474)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:461)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:371)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:201)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: Caused by: java.lang.IllegalStateException: Not a JSON Object: [{"name":"java.io.FileDescriptor","fields":[{"name":"fd"}],"methods":[{"name":"attach","parameterTypes":["java.io.Closeable"]}]},{"name":"java.lang.Boolean","methods":[{"name":"getBoolean","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.IllegalStateException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.IndexOutOfBoundsException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.Integer","methods":[{"name":"<init>","parameterTypes":["int"]},{"name":"intValue","parameterTypes":[]}]},{"name":"java.lang.NullPointerException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.lang.ProcessBuilder$RedirectPipeImpl","fields":[{"name":"fd"}],"methods":[{"name":"<init>","parameterTypes":[]}]},{"name":"java.lang.String","methods":[{"name":"lastIndexOf","parameterTypes":["int"]},{"name":"substring","parameterTypes":["int"]}]},{"name":"java.lang.System","methods":[{"name":"getProperty","parameterTypes":["java.lang.String"]},{"name":"setProperty","parameterTypes":["java.lang.String","java.lang.String"]}]},{"name":"java.net.DatagramSocket"},{"name":"java.net.InetSocketAddress","fields":[{"name":"holder"}]},{"name":"java.net.InetSocketAddress$InetSocketAddressHolder","fields":[{"name":"port"}]},{"name":"java.net.NoRouteToHostException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.net.ServerSocket","fields":[{"name":"impl"}]},{"name":"java.net.Socket"},{"name":"java.net.SocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.net.SocketTimeoutException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"java.nio.channels.ClosedChannelException","methods":[{"name":"<init>","parameterTypes":[]}]},{"name":"java.nio.channels.spi.AbstractSelectableChannel","methods":[{"name":"removeKey","parameterTypes":["java.nio.channels.SelectionKey"]}]},{"name":"org.newsclub.net.unix.AFSelector$PollFd","fields":[{"name":"fds"},{"name":"ops"},{"name":"rops"}]},{"name":"org.newsclub.net.unix.AFTIPCSocketAddress"},{"name":"org.newsclub.net.unix.AFUNIXDatagramSocket"},{"name":"org.newsclub.net.unix.AFUNIXServerSocket"},{"name":"org.newsclub.net.unix.AFUNIXSocket"},{"name":"org.newsclub.net.unix.AFUNIXSocketAddress"},{"name":"org.newsclub.net.unix.AFUNIXSocketCredentials","fields":[{"name":"gids"},{"name":"pid"},{"name":"uid"}],"methods":[{"name":"setUUID","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.AddressUnavailableSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.AncillaryDataSupport","fields":[{"name":"ancillaryReceiveBuffer"},{"name":"pendingFileDescriptors"}],"methods":[{"name":"receiveFileDescriptors","parameterTypes":["int[]"]},{"name":"setTipcDestName","parameterTypes":["int","int","int"]},{"name":"setTipcErrorInfo","parameterTypes":["int","int"]}]},{"name":"org.newsclub.net.unix.InvalidArgumentSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.OperationNotSupportedSocketException","methods":[{"name":"<init>","parameterTypes":["java.lang.String"]}]},{"name":"org.newsclub.net.unix.tipc.AFTIPCDatagramSocket"},{"name":"org.newsclub.net.unix.tipc.AFTIPCGroupRequest","methods":[{"name":"fromNative","parameterTypes":["int","int","int","int"]},{"name":"getFlagsValue","parameterTypes":[]},{"name":"getInstance","parameterTypes":[]},{"name":"getScopeId","parameterTypes":[]},{"name":"getType","parameterTypes":[]}]},{"name":"org.newsclub.net.unix.tipc.AFTIPCSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKDatagramSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKSocket"},{"name":"org.newsclub.net.unix.vsock.AFVSOCKServerSocket"}]
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.lambda$scanDeps$5(DependencyLoaderImpl.java:287)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.falsepattern.lib.internal.impl.dependencies.DependencyLoaderImpl.scanDeps(DependencyLoaderImpl.java:309)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.falsepattern.lib.internal.asm.CoreLoadingPlugin.<clinit>(CoreLoadingPlugin.java:56)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	... 18 more
[22:13:19] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:77)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.SecurityManager.checkExit(SecurityManager.java:624)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Runtime.exit(Runtime.java:113)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.System.exit(System.java:1908)
[22:13:19] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
```

**Comment by FalsePattern** [comment]
@n0099 Please open a new issue next time.
